### ISSUE TITLE
Suggestion: Add some comments!

### ISSUE THREAD

**Issue by SillySailboat** [jeticg/Evangelion-Uebersicht-Widget#2]
Dear based jeticg,

There's nothing wrong with this widget, that I've seen. It's pretty damn cool, and while I've never read the manga, I am loving this fantastic widget. Please keep adding stuff! Your work is appreciated. I'm not going to lie: I can hardly read CSS/Java/Coffeescript. I'm a C/C++ programmer, but I managed to change around some of the string outputs and colors to my liking. I'm not entirely sure if this is possible in coffeescript, but maybe some line comments/comment directives at the top of the file could point the customization crazies to the right element they need to change to get what they want (ex: change German to English or change cell and font colors). Again, just a suggestion, not an issue.

Keep it up m80

**Comment by jeticg** [comment]
Hello,
Thanks for the advise! I’ll add more comments on the next update (0.61a). I didn’t bother with this because this widget is still under development. Anyway, I’ll send you a email as soon as the update is ready, thank you for your support, it means a lot to me.
Cheers,
Jetic

**Comment by jeticg** [comment]
I've already uploaded the 0.61a, if there's anything you need do not hesitate to contact me, and I'll see what I can do. Thank you for your support!
