### ISSUE TITLE
I want to contribute translations.

### ISSUE THREAD

**Issue by zoenglinghou** [jeticg/Evangelion-Uebersicht-Widget#21]
I am enjoying the German and English version of the widget so far! I want to add simplified Chinese translations. Would that be welcomed?

**Comment by jeticg** [comment]
Hi. I had actually tried to do so but only with very poor results. It is mainly that I couldn't figure out a decent way to arrange the text. If you think you have ideas to make it work, you are of course welcome.

**Comment by zoenglinghou** [comment]
I am actually not sure how to change the font style for the cjk characters in the `if` statement (not really a developer). I would appreciate it if you can give me some hints...

**Comment by jeticg** [comment]
The font style is not the biggest issue though. It's the size of the Chinese characters. I speak Chinese very well so, if you have a design in mind I can help you implement it.
