### ISSUE TITLE
Widgets are left Justified

### ISSUE THREAD

**Issue by bcr-ch** [jeticg/Evangelion-Uebersicht-Widget#23]
From the screenshots I've seen the top half is usually at the right of the screen.  Not sure if there is something I need to configure.  Screenshot attached to show version / my view
<img width="1430" alt="ubersicht" src="https://user-images.githubusercontent.com/57232475/74583338-5a942a80-4fc6-11ea-8ca1-372680dfb531.png">

**Comment by jeticg** [comment]
This might be caused by having other conflicting widget maybe? I am not sure how to replicate this error.
