### ISSUE TITLE
Suggestion for battery

### ISSUE THREAD

**Issue by pelmeniboiler** [jeticg/Evangelion-Uebersicht-Widget#30]
In the show, the evangelions have their own UI for the battery with the clock and internal/external power indicator. OS X already does the math for the battery time remaining, I think it could be cool to replicate this. I understand if it doesn't necessarily fit with the honeycomb.

**Comment by jeticg** [comment]
It does pops up when the battery level is low. I find having an actual timer sometimes distracting for me, but if you want to make it permanent it's probably very easy to do as well.

**Comment by pelmeniboiler** [comment]
Oh! very cool! Haha I should try unplugging my laptop for once!
