### ISSUE TITLE
[REQ] Battery Stats (KB & Mouse/Trackpad)

### ISSUE THREAD

**Issue by hreality** [jeticg/Evangelion-Uebersicht-Widget#7]
Could you incorporate BT keyboard and trackpad battery stats please?

**Comment by jeticg** [comment]
This would be a bit tricky since not everyone uses bluetooth keyboard and trackpads, and some even use multiple bluetooth keyboards and trackpads. For that, I have no desire for adding this feature as of this moment. Thanks for understanding.
