### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by darkmatter** [jeticg/Evangelion-Uebersicht-Widget#8]
Great looking Widget. However, none of the clickable functions work. Meaning, none of them are triggered at all. 

Any ideas?

**Comment by jeticg** [comment]
This problem is caused by your übersicht setting. Normally, you need to press a button to be able to interact with the widget. You can check that out in your übersicht settings.

**Comment by darkmatter** [comment]
Oh you know what, I'm an idiot. I should've thought of that. I've been playing with Ubersicht all day and I'm so saturated by it I forgot the simplest thing. 

Great widget, thanks!

**Comment by jeticg** [comment]
You're welcome
