### ISSUE TITLE
internet speed shown as 0 in sierra

### ISSUE THREAD

**Issue by noirchen** [jeticg/Evangelion-Uebersicht-Widget#9]
After upgrading to sierra, the internet speed is shown as 0.

**Comment by jeticg** [comment]
Sorry but I am going to need a bit more information. Would you mind clicking on cell 32 and give me the output here?

Von meinem iPhone gesendet

**Comment by noirchen** [comment]
It shows something like

```
21.6 4 109.1 0B 0 0 0 ~ ~ ~ 0 ~ 0 Macintosh HD@
```

**Comment by jeticg** [comment]
Wait, what version of this widget are you running?

Von meinem iPhone gesendet

**Comment by noirchen** [comment]
Lasted 0.97a

**Comment by jeticg** [comment]
That's wired. I haven't encountered this problem before. The widget is running the following command to retrieve network traffic info:
`sar -n DEV 1 1 2>/dev/null | grep Average| awk 'BEGIN { sum = 0; sum2 = 0 }  { sum += $4;sum2 += $6 }; END { print sum,sum2 }'`
If you can get two positive output out of this command, then it should be working just fine, we'll have to dig in further. If this command gives you two zeros, then I don't think there's much I can do for you.

**Comment by noirchen** [comment]
OK I see. The newest sierra system removed sysstat command, so the output of the command you gave is two zeros. Maybe there is a replacement utility somewhere in the system.

**Comment by jeticg** [comment]
Strange. My Sierra somehow works just fine. I'll see what I can do. Will get back to you in a few hours.(two classes)

**Comment by jeticg** [comment]
@noirchen after hours of digging, I am unable to come up with an easy solution. However, I will keep looking for replacement commands.

**Comment by incredibleweirdo** [comment]
Hello - 
I see that the maintainer of the network-throughput widget is using the netstat command, and parsing that. However he seems to have included a binary executable (.out) file in his widget that does the parsing. 
I may see if I can get anything useful out of netstat with some grep. If I make any progress, I'll share it.

**Comment by jeticg** [comment]
@incredibleweirdo Thanks a million! I kind of wanted to do something about it myself but ended up being too busy to actually do so. I guess the fact that most of my computers are still running El Capitan kind of made me forget.

**Comment by incredibleweirdo** [comment]
Okay, I must admit I am not much of a terminal user, and this is much trial and error in the shell:

```
netstat -i -b | awk '{if ($4 > 0 && $7 > 0 && $10 > 0 && $1 != "lo0") print $1, $7, $10}'| uniq | awk '{sum1 += $2} {sum2 += $3} END {print sum1, sum2}'
```

Firstly, the arguments -i -b for netstat tell it to return the total IBytes and OBytes for each interface. Then pipe to awk to filter only for interfaces with values, and not the local loopback interface, return the name, IBytes, and OBytes. Then piped to 'uniq' for only unique rows (en1 for instance could be listed multiple times, with same usage, for different hostname/IP). lastly, back to awk to sum the IBytes and OBytes in the case that you do have multiple interfaces working. 

Probably needs a sanity check - not 100% on filtering out loopback, so probably needs comparing with results on El Capitan or older (I won't be near my work El Capitan machine until Monday).

Let me know if this helps.

**Comment by jeticg** [comment]
Well, I have tried netstat before but sadly the results that I got wasn't all that promising. By running your command I got the output 40573278367 1677719516, but the fact is that I was not doing anything at the moment, which matched the output of sar(0 0).

**Comment by incredibleweirdo** [comment]
Just goes to show how much I know about the terminal. Sorry for the confusion and misdirection.

After looking again, I was mistaken in thinking that the maintainer of network-throughput is using a binary file (my poor terminal/shell experience showing here). He's taking output of netstat -w1 (outputs IBytes/OBytes each second) into a file, ending in .out, then cat'ing that for columns 3 and 6. Much simpler. 

```
#!/bin/bash
function getBytes {
    netstat -w1 > network-throughput.widget/lib/network.out & sleep 1.5; kill $!;
}
BYTES=$(getBytes > /dev/null);
BYTES=$(cat network-throughput.widget/lib/network.out | grep '[0-9].*');
BYTES=$(echo $BYTES | awk '{print $3 "^" $6}');
echo $BYTES;
```

**Comment by jeticg** [comment]
Thanks to you, I think I have an idea now! Wonderful!

**Comment by jeticg** [comment]
@incredibleweirdo I just uploaded an updated version of my widget which should have resolved the issue. Feel free to try it out!

**Comment by incredibleweirdo** [comment]
Perfect! 
![screenshot_10_15_16__2_21_pm](https://cloud.githubusercontent.com/assets/1223976/19413469/b10c5d3c-92e2-11e6-8159-c20ff9308163.png)
